### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by JanX2**
Please follow the new instructions in the README for this to build.

### CODE REVIEW

**Comment by heatherleaf** [comment]
I cannot get this to build. The UniversalDetector doesn't get automatically downloaded to External/UniversalDetector, so XCode complains.

Also, the README file is not updated, so there are no new instructions there.

**Comment by JanX2** [comment]
Am 12.11.2012 um 14:30 schrieb Peter Ljunglöf:

> I cannot get this to build. The UniversalDetector doesn't get automatically downloaded to External/UniversalDetector, so XCode complains.
> 
> Also, the README file is not updated, so there are no new instructions there.
> Uh. Sorry. This is standard git:

git submodule update --init --recursive

**Comment by heatherleaf** [comment]
Ok, now XCode compiles without problems. Do you know if UniversalDetector works with 10.6? Because that's the current "OSX Deployment Target". (I guess it should do, since it compiles, but I don't know how XCode is in this).

**Comment by heatherleaf** [comment]
Do I need to do this regularly:

```
git submodule update --init --recursive
```

Or does it work like magic? 

Could you add some instructions in the README file for git newbies. What they should do to mirror the source code and build the program themselves? Thanks

**Comment by JanX2** [comment]
Am 12.11.2012 um 14:57 schrieb Peter Ljunglöf:

**Comment by JanX2** [comment]
Am 12.11.2012 um 14:59 schrieb Peter Ljunglöf:

> Do I need to do this regularly:
> 
> git submodule update --init --recursive
> 
> Or does it work like magic?
> No magic, sadly.

Simply put it works like this: one commiter adds a submodule. The parent repo stores the SHA1 of the current head of the subrepo and a URL where that repo/commit can be obtained. So you will only have to `git submodule update --init --recursive
` once, but `git submodule update` every time a new commit in the submodule is referenced (which for UniversalDetector should be very rarely).

**Comment by heatherleaf** [comment]
Looks good, thanks!

**Pull request merged**
