### PR TITLE
Support for MPlayerX

### PR DESCRIPTION
**Pull request by dusek**
Supporting movie name requires additions to MPlayerX scripting suite which
I hope to look at sometime soon. In the meantime, it says "Some Movie".

### CODE REVIEW

**Comment by heatherleaf** [comment]
Thanks! There are some conflicts now that I have merged the iTunes branch. Could you fix these please?

**Comment by dusek** [comment]
Yep, will get to it later today (evening CEST)

**Comment by dusek** [comment]
I rebased it and did git push --force.

**Comment by heatherleaf** [comment]
Thanks! Nice to see that someone is actually using this app :)

**Pull request merged**
